### ISSUE TITLE
AssertionError: image size must be a power of 2

### ISSUE THREAD

**Issue by TKassis** [lucidrains/lightweight-gan#10]
Thanks for this implementation, looks very promising. It's training much faster than the stylegan2-pytorch.

Release 0.9 was working well but now with 0.9.1 I get the following error no matter what image size I use:

` File "c:\users\timothy\miniconda3\envs\lwgan\lib\site-packages\lightweight_gan\lightweight_gan.py", line 308, in __init__
    assert is_power_of_two(resolution), 'image size must be a power of 2'
AssertionError: image size must be a power of 2`

**Comment by lucidrains** [comment]
@TKassis Hey Timothy! Sorry, introduced a bug lol https://github.com/lucidrains/lightweight-gan/releases/tag/0.9.2
