### ISSUE TITLE
Difference in Hinge Gan Loss compute

### ISSUE THREAD

**Issue by ericlearning** [lucidrains/lightweight-gan#11]
While checking the author's code from the supplementary material https://openreview.net/forum?id=1Fqg133qRaI, I noticed that they compute the hingegan loss not in the form of **relu(1 - pred)**, but instead **relu(0.2*rand + 0.8 - pred)**.

Is this some sort of a regularization? I've never seen this done before.

**Comment by lucidrains** [comment]
Wow I've never seen that before! Maybe I'll send the author an email if I can't figure it out

**Comment by lucidrains** [comment]
The author responded  :D

```The hinge loss I used involves a label-smoothing trick, which actually seems not adding any performance.```
