### ISSUE TITLE
Shape mismatch, can't divide axis of length 3 in chunks of 2

### ISSUE THREAD

**Issue by TKassis** [lucidrains/lightweight-gan#12]
I'm running with the following arguments:

`lightweight_gan --data images --image-size 1024 --aug-prob 0.2 --batch-size 16 --gradient-accumulate-every 4 --attn-res-layers [32,64] --amp`

But getting the following error:

`einops.EinopsError:  Error while processing rearrange-reduction pattern "b (g c) h w -> b g c h w".
 Input tensor shape: torch.Size([16, 3, 512, 512]). Additional info: {'g': 2}.
 Shape mismatch, can't divide axis of length 3 in chunks of 2`

**Comment by TKassis** [comment]
I don't get that error when I specific --image-size to be 512.

**Comment by lucidrains** [comment]
@TKassis thank you! https://github.com/lucidrains/lightweight-gan/releases/tag/0.11.3 should be fixed :D

**Comment by lucidrains** [comment]
@TKassis do share your results, if you can :)
