### ISSUE TITLE
Can't find "__main__" module (sorry if noob question)

### ISSUE THREAD

**Issue by SPotaufeux** [lucidrains/lightweight-gan#127]
Hello, I hope it's not too much of a noob question, I don't have any background in coding.

After creating the env and installing Pytorch I ran "python setup.py install" and then I ran "python lightweight_gan --data /source --image-size 512" (I filled a "source" folder with pictures of fishes) but I get the error "can't find '__main__' module".
More exactly,
C:\Programmes perso\Logiciels\Anaconda\envs\lightweightgan\python.exe: can't find '__main__' module in 'C:\\Programmes perso\\Logiciels\\LightweightGan\\lightweight_gan'
I tried to copy and rename some of the other modules (__init__, lightweight_gan...), the code seems to start to run but stops before doing anything. So I guess some file must be missing, or did I do something wrong ?

Thanks a lot for the repo and have a nice day

**Comment by rgaiacs** [comment]
After you install this package (`python setup.py install`), you should use

```
lightweight_gan --data /source --image-size 512
```

instead of

```
python lightweight_gan --data /source --image-size 512
```

**Comment by SPotaufeux** [comment]
That was the issue, thanks !

**Comment by rgaiacs** [comment]
@SPotaufeux can you close the issue?

**Comment by SPotaufeux** [comment]
Ah, yes
