### ISSUE TITLE
Using lightweight-gan with Colab ?

### ISSUE THREAD

**Issue by 7khalil** [lucidrains/lightweight-gan#13]
Hi, do you have plan to add google colab notebook for this work ?

**Comment by lucidrains** [comment]
@7khalil sure! I mean, you just have to download all the images to a folder and run one command

**Comment by lucidrains** [comment]
@7khalil do you really think it needs a colab?

**Comment by 7khalil** [comment]
@lucidrains  actualy i have tried it, and i got with a dataset of ~1300 images, i got GPU memory overflow. after reading your comment i the tried it with a smaller dataset with 500 images and it seems to work well.

**Comment by lucidrains** [comment]
@7khalil ohh, what sized images did you try to train? you shouldn't overflow with anything below or at 512x512

**Comment by lucidrains** [comment]
@7khalil the dataset size doesn't determine the amount of GPU memory used, it's the batch size and image resolution that are the determinants

**Comment by 7khalil** [comment]
@lucidrainsit seems weird, because both datasets that i used are 1024px resolution. wondering why ?!

**Comment by ClashLuke** [comment]
[pin_memory=True is set to True](https://github.com/lucidrains/lightweight-gan/blob/main/lightweight_gan/lightweight_gan.py#L907). This is a trick used to disable constant freeing and reallocating of memory by PyTorch, therefore improving the training speed by a bit. Usually, pinning the memory improves the speeds by something around 1% to 15%. If you're facing GPU memory issues, perhaps turning this flag off would be a good first step.

**Comment by 7khalil** [comment]
Ok, @ClashLuke thanks.
