### ISSUE TITLE
Doesn't detect CUDA from Nvidia GPU

### ISSUE THREAD

**Issue by demiahmed** [lucidrains/lightweight-gan#130]
Error when trying to run lightweight_gan from the command line, I am getting the error

``` You need to have an Nvidia GPU with CUDA installed ```

Although running ```torch.cuda.is_available()``` returns ```True```

![image](https://user-images.githubusercontent.com/40930082/173759360-f30292c9-1d08-4aa7-b9ad-dee15f74e473.png)

**Comment by Paillat-dev** [comment]
Hello, I have the same problem, but for me it returns false, while I have already installed cuda.
