### ISSUE TITLE
Why you have normalize after init conv and why dim -1?

### ISSUE THREAD

**Issue by hadaev8** [lucidrains/lightweight-gan#17]
https://github.com/lucidrains/lightweight-gan/blob/main/lightweight_gan/lightweight_gan.py#L408

**Comment by lucidrains** [comment]
@hadaev8 ohh, you found a :beetle: lol

https://github.com/lucidrains/lightweight-gan/releases/tag/0.12.4

I was trying to do pixel normalization, as they did in stylegan
