### ISSUE TITLE
What is sle_spatial?

### ISSUE THREAD

**Issue by woctezuma** [lucidrains/lightweight-gan#20]
I have seen this function argument mentioned in this issue:

https://github.com/lucidrains/lightweight-gan/issues/14#issuecomment-733432989

What is `sle_spatial`?

**Comment by woctezuma** [comment]
Oops.

![SLE](https://i.imgur.com/fzpSssm.png)

**Comment by woctezuma** [comment]
I realise this explains what SLE means, but not whether I should activate Spatial SLE.

https://github.com/lucidrains/lightweight-gan/blob/9a48e878255a0624a4696f5a60fd7bde6eaef4a8/lightweight_gan/lightweight_gan.py#L273-L295

https://github.com/lucidrains/lightweight-gan/blob/9a48e878255a0624a4696f5a60fd7bde6eaef4a8/lightweight_gan/lightweight_gan.py#L296-L322

**Comment by woctezuma** [comment]
I see you mention spatial SLE here: https://github.com/lucidrains/lightweight-gan/projects/1#card-49486796

With a reference to: https://arxiv.org/abs/1807.06521

**Comment by bogdan-ivan** [comment]
I have seen in your thread "Optimal parameters for Google Colab" that you ended up dropping sle_spatial, have you noticed a difference in the results ?

**Comment by woctezuma** [comment]
> I have seen in your thread "Optimal parameters for Google Colab" that you ended up dropping sle_spatial, have you noticed a difference in the results ?

No, I cannot talk about that. I dropped this parameter for now only because:
-   I was not sure about its effect,
-   I wanted to have a the simplest command-line possible, to make sure that the long run-times were not due to my choice of command-line options.

**Comment by lucidrains** [comment]
There's a bug in my code and SLE spatial is always on 🙈🙈

**Comment by lucidrains** [comment]
ok, sle-spatial should be fixed in the latest version

**Comment by lucidrains** [comment]
SLE spatial is basically squeeze excitation, but done in the spatial dimension rather than the channel dimension

**Comment by Dok11** [comment]
> There's a bug in my code and SLE spatial is always on 🙈🙈

@lucidrains why SLE spatial disabled by default?
