### ISSUE TITLE
Why have the hamburger layers been removed?

### ISSUE THREAD

**Issue by Mut1nyJD** [lucidrains/lightweight-gan#22]
More a curious question:

I remember In an earlier version of this repository there were hamburger attention layers used for the attention layers but these have later replaced with global self attention, I am just curious why?

Where the hamburger attention layers not good or did not lead to any improvements in training or visual quality?

**Comment by lucidrains** [comment]
@Mut1nyJD hamburger didn't work as well for me as linear attention :(

Attention is still all we need.

**Comment by Mut1nyJD** [comment]
@lucidrains ah okay I see thank you
