### ISSUE TITLE
Losses

### ISSUE THREAD

**Issue by woctezuma** [lucidrains/lightweight-gan#23]
I think it is not clear what the losses displayed in the log are.

https://github.com/lucidrains/lightweight-gan/blob/9a48e878255a0624a4696f5a60fd7bde6eaef4a8/lightweight_gan/lightweight_gan.py#L1184-L1191

My understanding is that, in `G: 1.37 | D: 1.80 | GP: 0.97 | SS: 0.02`, we have:

- the loss $L_G$ for the Generator (G),
- the (total) loss $L_D$ for the Discriminator (D),
- a loss from Gradient Penalty (GP),
- a reconstruction loss from the Self-Supervision (SS) of the the discriminator.

It would be nice to mention it somewhere so that we can try to understand what happens during training. :)

**Comment by fabiooshiro** [comment]
A noob question: what is a good/bad result range?
