### ISSUE TITLE
Greyscale image generation

### ISSUE THREAD

**Issue by stefanorosss** [lucidrains/lightweight-gan#24]
Hi, 

thank you for this repo, I've been playing with it a bit and it seems very good!
I am trying to generate greyscale images, so I modified the channel accordingly 

`init_channel = 4 if transparent else 1`

unfortunately, this seemed to have no effect as the images generated are still RGB (even though they converge towards greyscale with time), even weirder IMO is that I can modify the number of channels for the generator and keep the original 3 for the discriminator without any issue. 

I have also changed this part to no effect

`convert_image_fn = partial(convert_image_to, 'RGBA' if transparent else 'L') `
`num_channels = 1 if not transparent else 4`
 
Am I missing something here?

**Comment by woctezuma** [comment]
Just a quick comment: wouldn't it have been simpler to edit the logic the other way around? Rather than keeping "transparent" and replacing RGB with grayscale, you could have kept RGB and replaced "transparent" with "grayscale". In this case, all you would have to do is Ctrl+F "transparent" (32 matches) in https://github.com/lucidrains/lightweight-gan/blob/main/lightweight_gan/lightweight_gan.py and change the logic every time.

**Comment by stefanorosss** [comment]
You are definitely right! I started with the assumption of wanting to change from RGB and didn't question it later, thanks

**Comment by bogdan-ivan** [comment]
This would be great to be added as an option. @lucidrains

**Comment by lucidrains** [comment]
@bogdan-ivan sure, i'll add it! what is the corresponding enum string in pillow for greyscale? (like `RGBA` is for transparent)

**Comment by woctezuma** [comment]
> @bogdan-ivan sure, i'll add it! what is the corresponding enum string in pillow for greyscale? (like `RGBA` is for transparent)

The last time I checked, it was `L`.

**Comment by lucidrains** [comment]
https://github.com/lucidrains/lightweight-gan/releases/tag/0.14.0 ok done with the `--greyscale` flag

**Comment by Dok11** [comment]
@lucidrains I think about `--num-channels` flag. For example to generation textures which contain several maps (albedo, roughness, specular, normal map). How do you think does possible modify code to work with them? And will it be too hard or easy?
