### ISSUE TITLE
Spectral Normalization

### ISSUE THREAD

**Issue by calvinpelletier** [lucidrains/lightweight-gan#29]
I noticed that the paper mentions spectral normalization (Miyato et al., 2018) but I don't see it used in your implementation. Have you tried it?

**Comment by lucidrains** [comment]
Hey! Yeah I did and I got worse results than gradient penalty. Then I read in the stylegan paper that they noticed the same and decided to keep GP instead

**Comment by calvinpelletier** [comment]
Thanks!
