### ISSUE TITLE
Troubles with global context module in 0.15.0

### ISSUE THREAD

**Issue by Dok11** [lucidrains/lightweight-gan#36]
@lucidrains 

After update to this version https://github.com/lucidrains/lightweight-gan/releases/tag/0.15.0 I cant continue train my network and did start in from zero.
Previous version was in state 117k batches by 4 (468k images, around 66 hours of trainig) image and was pretty good.
In new version 0.15.0 on same dataset with same parameters (--image-size 1024 --aug-types [color,offset_h] --aug-prob 1 --amp --batch-size 7) after 77k batches by 7 (539k images, around 49 hours of training) I see some bugs like oil puddle. Did you meet this or do you know how avoid this?

![image](https://user-images.githubusercontent.com/2697890/103443907-9aaedb00-4c74-11eb-97b6-ad3461f62bf3.png)

In previous version with sle-spatial I didnt meet something like this.

**Comment by lucidrains** [comment]
![141-ema](https://user-images.githubusercontent.com/108653/103445296-16823680-4c27-11eb-9b2f-4cbd6715d95d.jpg)

could it be one of your augmentations? I don't see that artifact, but i'm using only cutout and translation augmentations

**Comment by lucidrains** [comment]
i don't see that artifact even when i go back, so i assume its your augmentations leaking

your augmentation probability is set at 1, is that intentional?

**Comment by Dok11** [comment]
> your augmentation probability is set at 1, is that intentional?

Yes, this value was same in the previous run.

I need offset_h every time because it panoramas with seamless by horizont. But color aug can produce this bug as I think. Maybe I'll reduce probability only for color aug for test.

**Comment by Dok11** [comment]
Currently I think about external config with list of augs with probabilities for every of them 🤔 
It may be like this `--aug-config config.yml` with list of augs from albumentations https://albumentations-demo.herokuapp.com/ . Sounds like a plan for next PR =)

**Comment by lucidrains** [comment]
@Dok11 ok sounds good! keep me informed, if that artifact persists, i'll make global context module optional with a feature flag

i think GC makes more sense than the 4x4 average pooling before

**Comment by lucidrains** [comment]
https://github.com/lucidrains/lightweight-gan/commit/eaa76d42b6f27eda5e64d67a76c4440170d63330 i decided to switch back to squeeze excitations multiply by sigmoid output rather than addition of norm

**Comment by Dok11** [comment]
> eaa76d4 i decided to switch back to squeeze excitations multiply by sigmoid output rather than addition of norm

Do you have some test to see how it will change training process or result? And will I can resume training network created on 0.15 if I'll update library to 0.16?

**Comment by lucidrains** [comment]
@Dok11 you'll have to retrain unfortunately, or just stick with 0.15

i'm retraining now, but i'm pretty sure it'll be artifact free since the sigmoid bounds the channel modulation

**Comment by Dok11** [comment]
You right. After 15k steps by batch size 9 the oil puddles was gone.
