### ISSUE TITLE
Training finished but result not very good

### ISSUE THREAD

**Issue by jinfagang** [lucidrains/lightweight-gan#38]
![139-ema](https://user-images.githubusercontent.com/21303438/103736061-6d727c00-502a-11eb-8c4e-88f38bf790e1.jpg)
![139](https://user-images.githubusercontent.com/21303438/103736066-6fd4d600-502a-11eb-8276-10bf3ef7e64e.jpg)

this is the best result I got.

Seems not very good? @lucidrains

**Comment by woctezuma** [comment]
For comparison:

![Figure 1 in the paper](https://i.imgur.com/5eGURFi.png)

![Figure 6 in the paper](https://i.imgur.com/Oh5WD5r.png)

**Comment by Dok11** [comment]
@jinfagang you can use https://github.com/lucidrains/stylegan2-pytorch

**Comment by lucidrains** [comment]
@jinfagang keep training for longer (`--num-train-steps`) - add more attention :D

**Comment by lucidrains** [comment]
![Uploading 294-ema.jpg…]()

**Comment by jinfagang** [comment]
thank u guys. It seems styleganv2 can get a better result

**Comment by Dok11** [comment]
@jinfagang on the other hand you can create plot with FID of your model and check doest is still improve quality. If yes you can resume training
