### ISSUE TITLE
What is the differenece between dataset_aug_prob and aug_prob?

### ISSUE THREAD

**Issue by Dok11** [lucidrains/lightweight-gan#42]

**Comment by lucidrains** [comment]
So the dataset one augments the images non-differentiably at the start, while the other augments everything going into the discriminator, generated or not

**Comment by Dok11** [comment]
Is im right? dataset_aug_prob — for generator and discriminator, aug_prob — for discriminator only?
And why dataset_aug_prob qualt to 0 by default? Is it reccomend value?

**Comment by woctezuma** [comment]
The recommendation is to use differentiable augmentations.

> S. Zhao, Z. Liu, J. Lin, J.-Y. Zhu, and S. Han. Differentiable augmentation for data-efficient GAN training.CoRR, [abs/2006.10738](https://arxiv.org/abs/2006.10738), 2020

> The performance of generative adversarial networks (GANs) heavily deterioratesgiven a limited amount of training data. This is mainly because the discriminatoris memorizing the exact training set.  To combat it, we proposeDifferentiableAugmentation(DiffAugment), a simple method that improves the data efficiency ofGANs by imposing various types of differentiable augmentations on both real andfake samples. Previous attempts to directly augment the training data manipulatethe distribution of real images, yielding little benefit; DiffAugment enables us toadopt the differentiable augmentation for the generated samples, effectively stabi-lizes training, and leads to better convergence.

https://github.com/mit-han-lab/data-efficient-gans

**Comment by Dok11** [comment]
If it so helpuful why default value is zero? https://github.com/lucidrains/lightweight-gan/blob/main/lightweight_gan/cli.py#L100

**Comment by lucidrains** [comment]
@Dok11 what woc is saying is that the new paper says the dataset augmentations are not helpful

We should be using the differentiable one (the one you have been working on) as much as possible

**Comment by Dok11** [comment]
Thank you, now thats clear! =)
