### ISSUE TITLE
FID calculation arguments missing device?

### ISSUE THREAD

**Issue by cr458** [lucidrains/lightweight-gan#45]
The args to calculate_fid_given_paths are given here
https://github.com/lucidrains/lightweight-gan/blob/7c16bed71fa55cb8fb07f4b8ff1b89eb4fd0f984/lightweight_gan/lightweight_gan.py#L1160

However looking at the implementation in pytorch-fid, it seems to expect the device rather than the bool passed above:
https://github.com/mseitzer/pytorch-fid/blob/master/src/pytorch_fid/fid_score.py#L240
`def calculate_fid_given_paths(paths, batch_size, device, dims):`

**Comment by lucidrains** [comment]
ohh, i wonder if they changed that recently, ok i made the fix at https://github.com/lucidrains/lightweight-gan/releases/tag/0.16.3

**Comment by cr458** [comment]
@lucidrains Wow that was fast, thanks! FYI I noticed your stylegan2 implementation uses the same code so it may be worth checking that still works too!

**Comment by lucidrains** [comment]
Will do! Thanks!
