### ISSUE TITLE
Getting NoneType is not subscriptable when trying to start training.

### ISSUE THREAD

**Issue by TomCallan** [lucidrains/lightweight-gan#48]
I've been able to train models before but after changing my dataset I'm getting the error.

My trace:
File "/usr/local/lib/python3.6/dist-packages/lightweight_gan/lightweight_gan.py", line 1356, in load
    name = checkpoints[-1]
TypeError: 'NoneType' object is not subscriptable

**Comment by woctezuma** [comment]
That would indicate that `checkpoints` is `None`.

**Comment by TomCallan** [comment]
> That would indicate that `checkpoints` is `None`.

I know that but the bit confusing me is that I'm not specifying a checkpoint because it hasn't been run yet.
I'm just running: lightweight_gan --data /path/ --amp --disc-output-size 5

**Comment by woctezuma** [comment]
Try specifying a different.

It seems the program is trying to load a previous checkpoint:

https://github.com/lucidrains/lightweight-gan/blob/dd235e8da96bb9cb19c7b2de9bb244ea81f9fb8d/lightweight_gan/lightweight_gan.py#L1350-L1357

But it finds no checkpoint in the folder, so it returns without any content here:

https://github.com/lucidrains/lightweight-gan/blob/dd235e8da96bb9cb19c7b2de9bb244ea81f9fb8d/lightweight_gan/lightweight_gan.py#L1377-L1384

**Comment by lucidrains** [comment]
@TomCallan oh oops, I think a recent change from @Dok11 may have broke it

do you want to try https://github.com/lucidrains/lightweight-gan/releases/tag/0.17.3 and let me know if that fixes things?

**Comment by TomCallan** [comment]
> do you want to try https://github.com/lucidrains/lightweight-gan/releases/tag/0.17.3 and let me know if that fixes things?
This fixed it, as did adding the --new flag.

**Comment by Dok11** [comment]
Sorry, I though my refactor was correct
https://github.com/lucidrains/lightweight-gan/commit/be04b2191e975f382708ce0e9f62502607ebd860
