### ISSUE TITLE
[Question] Change in performance

### ISSUE THREAD

**Issue by bogdan-ivan** [lucidrains/lightweight-gan#5]
Updating from version 0.5.6 to the latest release 0.6.1 (at the time of this post) I've noticed a 2x increase in seconds/it using the same settings on the same dataset.
Is this expected behavior considering the changes made ?

**Comment by lucidrains** [comment]
@bogdan-ivan I went back to gradient penalty because spectral norm wasn't working for me for some reason, but let me try it again today

**Comment by lucidrains** [comment]
@bogdan-ivan I removed the gradient penalty in favor of weight normalization, do you want to update and try again?

https://github.com/lucidrains/lightweight-gan/releases/tag/0.7.0

**Comment by lucidrains** [comment]
@bogdan-ivan nevermind, i went back to GP because i was seeing early divergence with anything else
