### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by ramnoob** [lucidrains/lightweight-gan#52]
Thx great GAN!
Run  `lightweight_gan --data ./path/to/images --image-size 512` , an error occurs.
`BrokenPipeError: [Errno 32] Broken pipe`

Probably due to the behavior of num_workers in pytorch on win10.
Is there any way to solve this?

**Comment by lucidrains** [comment]
@ramnoob hey thanks! i've added a `--num-worker` flag so you can specify the number of workers in 0.17.6

let me know if that works!

**Comment by ramnoob** [comment]
Thanks for the quick response!
The above phenomenon was occurring in the conda environment.
But then I started training in a pure Win10 CMD environment and it ran fine.
Training is expected to take a week.
After the training, I'll try ver0.17.6 in conda environment.

**Comment by ramnoob** [comment]
@lucidrains  Hello!
I upgraded the version to 0.17.6 and ran it in the conda environment, but it doesn't seem to work.
`Lightweight_gan --data datasets --image-size 512 --num-worker 1`  I get the same `[Errno 32] Broken pipe`.
However, it works well in the WindowsCMD environment, so I am not troubled!

I think it would be better if a learning rate curve could be obtained at running or the end of the run, so please consider implementing it if you have enough capacity!
