### ISSUE TITLE
Regarding implementation of attn layers in discriminator

### ISSUE THREAD

**Issue by ferrophile** [lucidrains/lightweight-gan#69]
I noticed a slight difference in implementation of generator and discriminator.

Lines 423-424, `Generator.__init__`
```
for (res, (chan_in, chan_out)) in zip(self.res_layers, in_out_features):
    image_width = 2 ** res
```

Lines 569-570, `Discriminator.__init__`
```
for (res, ((_, chan_in), (_, chan_out))) in zip(non_residual_resolutions, chan_in_out):
    image_width = 2 ** resolution
```

Is the latter a typo? `resolution` is tied to `log2(image_size)` and does not change in the for loop.

**Comment by lucidrains** [comment]
@ferrophile Hi Hong! You indeed caught a bug :pray: thank you so much! I've fixed it in 0.18
