### ISSUE TITLE
ImportError: cannot import name 'filter2D' from 'kornia'

### ISSUE THREAD

**Issue by Volta1r3** [lucidrains/lightweight-gan#90]
Had this issue when I tried to train. Replace "from kornia import filter2D" with "from kornia import filter2d"

**Comment by matteopantano** [comment]
How did you solve this problem?

**Comment by mah1212** [comment]
```cannot import name 'filter2d' from partially initialized module 'kornia' (most likely due to a circular import) (path\to\site-packages\kornia\__init__.py)```

Edit __init__.py and use 
```from kornia.filters import filter2d```

**Comment by matteopantano** [comment]
Thanks, it works!

**Comment by quickgrid** [comment]
I am still getting this error with `kornia=0.6.1` and `lightweight_gan=0.20.5`. Replacing `from kornia import filter2d` with `from kornia.filters import filter2d` in **ligweight_gan.py** and removing `from kornia.filters import filter2d` from `__init__.py` worked for me.
